services:
  - type: web
    name: mini-netflix-api
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: mini-netflix-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mini-netflix-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: mini-netflix-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mini-netflix-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: mini-netflix-db
          property: database
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: mini-netflix-db
    databaseName: mini_netflix
    user: mini_netflix_user
    plan: free
    region: oregon